// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Bullet
    {
        [DataMember(Name = "bullet_id")]
        public int BulletId;
        [DataMember(Name = "bullet_name")]
        public string BulletName;
        [DataMember(Name = "distance")]
        public float Distance;
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "position")]
        public DbVector2 Position;
        [DataMember(Name = "direction")]
        public DbVector2 Direction;

        public Bullet(
            int BulletId,
            string BulletName,
            float Distance,
            float Speed,
            DbVector2 Position,
            DbVector2 Direction
        )
        {
            this.BulletId = BulletId;
            this.BulletName = BulletName;
            this.Distance = Distance;
            this.Speed = Speed;
            this.Position = Position;
            this.Direction = Direction;
        }

        public Bullet()
        {
            this.BulletName = "";
            this.Position = new();
            this.Direction = new();
        }
    }
}
