// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CharacterLevelDataConfig
    {
        [DataMember(Name = "level")]
        public int Level;
        [DataMember(Name = "exp")]
        public int Exp;

        public CharacterLevelDataConfig(
            int Level,
            int Exp
        )
        {
            this.Level = Level;
            this.Exp = Exp;
        }

        public CharacterLevelDataConfig()
        {
        }
    }
}
