// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class DbChest
    {
        [DataMember(Name = "chest_id")]
        public int ChestId;
        [DataMember(Name = "item_id")]
        public int ItemId;
        [DataMember(Name = "position")]
        public DbVector2 Position;

        public DbChest(
            int ChestId,
            int ItemId,
            DbVector2 Position
        )
        {
            this.ChestId = ChestId;
            this.ItemId = ItemId;
            this.Position = Position;
        }

        public DbChest()
        {
            this.Position = new();
        }
    }
}
