// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Diamond
    {
        [DataMember(Name = "diamond_id")]
        public int DiamondId;
        [DataMember(Name = "position")]
        public DbVector2 Position;
        [DataMember(Name = "exp")]
        public int Exp;

        public Diamond(
            int DiamondId,
            DbVector2 Position,
            int Exp
        )
        {
            this.DiamondId = DiamondId;
            this.Position = Position;
            this.Exp = Exp;
        }

        public Diamond()
        {
            this.Position = new();
        }
    }
}
