// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GameConfigs
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "word_size")]
        public DbVector2 WordSize;

        public GameConfigs(
            int Id,
            DbVector2 WordSize
        )
        {
            this.Id = Id;
            this.WordSize = WordSize;
        }

        public GameConfigs()
        {
            this.WordSize = new();
        }
    }
}
