// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GunmanUser
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "user_id")]
        public int UserId;
        [DataMember(Name = "gold")]
        public int Gold;
        [DataMember(Name = "diamond")]
        public int Diamond;

        public GunmanUser(
            SpacetimeDB.Identity Identity,
            int UserId,
            int Gold,
            int Diamond
        )
        {
            this.Identity = Identity;
            this.UserId = UserId;
            this.Gold = Gold;
            this.Diamond = Diamond;
        }

        public GunmanUser()
        {
        }
    }
}
