// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MovementPlayerTimer
    {
        [DataMember(Name = "schedule_id")]
        public ulong ScheduleId;
        [DataMember(Name = "schedule_at")]
        public SpacetimeDB.ScheduleAt ScheduleAt;

        public MovementPlayerTimer(
            ulong ScheduleId,
            SpacetimeDB.ScheduleAt ScheduleAt
        )
        {
            this.ScheduleId = ScheduleId;
            this.ScheduleAt = ScheduleAt;
        }

        public MovementPlayerTimer()
        {
            this.ScheduleAt = null!;
        }
    }
}
