// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Player
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "player_id")]
        public int PlayerId;
        [DataMember(Name = "position")]
        public DbVector2 Position;
        [DataMember(Name = "attack_direction")]
        public DbVector2 AttackDirection;
        [DataMember(Name = "movement_direction")]
        public DbVector2 MovementDirection;
        [DataMember(Name = "level")]
        public int Level;
        [DataMember(Name = "user_id")]
        public int UserId;
        [DataMember(Name = "exp")]
        public int Exp;
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "is_movement")]
        public bool IsMovement;
        [DataMember(Name = "weapon_id")]
        public string WeaponId;

        public Player(
            SpacetimeDB.Identity Identity,
            int PlayerId,
            DbVector2 Position,
            DbVector2 AttackDirection,
            DbVector2 MovementDirection,
            int Level,
            int UserId,
            int Exp,
            float Speed,
            bool IsMovement,
            string WeaponId
        )
        {
            this.Identity = Identity;
            this.PlayerId = PlayerId;
            this.Position = Position;
            this.AttackDirection = AttackDirection;
            this.MovementDirection = MovementDirection;
            this.Level = Level;
            this.UserId = UserId;
            this.Exp = Exp;
            this.Speed = Speed;
            this.IsMovement = IsMovement;
            this.WeaponId = WeaponId;
        }

        public Player()
        {
            this.Position = new();
            this.AttackDirection = new();
            this.MovementDirection = new();
            this.WeaponId = "";
        }
    }
}
