// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DespawnDiamondHandler(ReducerEventContext ctx, int diamondId);
        public event DespawnDiamondHandler? OnDespawnDiamond;

        public void DespawnDiamond(int diamondId)
        {
            conn.InternalCallReducer(new Reducer.DespawnDiamond(diamondId));
        }

        public bool InvokeDespawnDiamond(ReducerEventContext ctx, Reducer.DespawnDiamond args)
        {
            if (OnDespawnDiamond == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDespawnDiamond(
                ctx,
                args.DiamondId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DespawnDiamond : Reducer, IReducerArgs
        {
            [DataMember(Name = "diamond_id")]
            public int DiamondId;

            public DespawnDiamond(int DiamondId)
            {
                this.DiamondId = DiamondId;
            }

            public DespawnDiamond()
            {
            }

            string IReducerArgs.ReducerName => "despawn_diamond";
        }
    }
}
