// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DespawnChestHandler(ReducerEventContext ctx, int chestId);
        public event DespawnChestHandler? OnDespawnChest;

        public void DespawnChest(int chestId)
        {
            conn.InternalCallReducer(new Reducer.DespawnChest(chestId));
        }

        public bool InvokeDespawnChest(ReducerEventContext ctx, Reducer.DespawnChest args)
        {
            if (OnDespawnChest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDespawnChest(
                ctx,
                args.ChestId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DespawnChest : Reducer, IReducerArgs
        {
            [DataMember(Name = "chest_id")]
            public int ChestId;

            public DespawnChest(int ChestId)
            {
                this.ChestId = ChestId;
            }

            public DespawnChest()
            {
            }

            string IReducerArgs.ReducerName => "despawn_chest";
        }
    }
}
