// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DespawnBulletHandler(ReducerEventContext ctx, int bulletId);
        public event DespawnBulletHandler? OnDespawnBullet;

        public void DespawnBullet(int bulletId)
        {
            conn.InternalCallReducer(new Reducer.DespawnBullet(bulletId));
        }

        public bool InvokeDespawnBullet(ReducerEventContext ctx, Reducer.DespawnBullet args)
        {
            if (OnDespawnBullet == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDespawnBullet(
                ctx,
                args.BulletId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DespawnBullet : Reducer, IReducerArgs
        {
            [DataMember(Name = "bullet_id")]
            public int BulletId;

            public DespawnBullet(int BulletId)
            {
                this.BulletId = BulletId;
            }

            public DespawnBullet()
            {
            }

            string IReducerArgs.ReducerName => "despawn_bullet";
        }
    }
}
