// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ShootingHandler(ReducerEventContext ctx, string bulletName, float distance, float speed, SpacetimeDB.Types.DbVector2 startPosition, SpacetimeDB.Types.DbVector2 direction);
        public event ShootingHandler? OnShooting;

        public void Shooting(string bulletName, float distance, float speed, SpacetimeDB.Types.DbVector2 startPosition, SpacetimeDB.Types.DbVector2 direction)
        {
            conn.InternalCallReducer(new Reducer.Shooting(bulletName, distance, speed, startPosition, direction));
        }

        public bool InvokeShooting(ReducerEventContext ctx, Reducer.Shooting args)
        {
            if (OnShooting == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnShooting(
                ctx,
                args.BulletName,
                args.Distance,
                args.Speed,
                args.StartPosition,
                args.Direction
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Shooting : Reducer, IReducerArgs
        {
            [DataMember(Name = "bullet_name")]
            public string BulletName;
            [DataMember(Name = "distance")]
            public float Distance;
            [DataMember(Name = "speed")]
            public float Speed;
            [DataMember(Name = "start_position")]
            public DbVector2 StartPosition;
            [DataMember(Name = "direction")]
            public DbVector2 Direction;

            public Shooting(
                string BulletName,
                float Distance,
                float Speed,
                DbVector2 StartPosition,
                DbVector2 Direction
            )
            {
                this.BulletName = BulletName;
                this.Distance = Distance;
                this.Speed = Speed;
                this.StartPosition = StartPosition;
                this.Direction = Direction;
            }

            public Shooting()
            {
                this.BulletName = "";
                this.StartPosition = new();
                this.Direction = new();
            }

            string IReducerArgs.ReducerName => "shooting";
        }
    }
}
