// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateDirectionHandler(ReducerEventContext ctx, SpacetimeDB.Types.DbVector2 movement, SpacetimeDB.Types.DbVector2 attackDirection);
        public event UpdateDirectionHandler? OnUpdateDirection;

        public void UpdateDirection(SpacetimeDB.Types.DbVector2 movement, SpacetimeDB.Types.DbVector2 attackDirection)
        {
            conn.InternalCallReducer(new Reducer.UpdateDirection(movement, attackDirection));
        }

        public bool InvokeUpdateDirection(ReducerEventContext ctx, Reducer.UpdateDirection args)
        {
            if (OnUpdateDirection == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateDirection(
                ctx,
                args.Movement,
                args.AttackDirection
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateDirection : Reducer, IReducerArgs
        {
            [DataMember(Name = "movement")]
            public DbVector2 Movement;
            [DataMember(Name = "attack_direction")]
            public DbVector2 AttackDirection;

            public UpdateDirection(
                DbVector2 Movement,
                DbVector2 AttackDirection
            )
            {
                this.Movement = Movement;
                this.AttackDirection = AttackDirection;
            }

            public UpdateDirection()
            {
                this.Movement = new();
                this.AttackDirection = new();
            }

            string IReducerArgs.ReducerName => "update_direction";
        }
    }
}
