// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateMovementHandler(ReducerEventContext ctx, SpacetimeDB.Types.DbVector2 direction);
        public event UpdateMovementHandler? OnUpdateMovement;

        public void UpdateMovement(SpacetimeDB.Types.DbVector2 direction)
        {
            conn.InternalCallReducer(new Reducer.UpdateMovement(direction));
        }

        public bool InvokeUpdateMovement(ReducerEventContext ctx, Reducer.UpdateMovement args)
        {
            if (OnUpdateMovement == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnUpdateMovement(
                ctx,
                args.Direction
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateMovement : Reducer, IReducerArgs
        {
            [DataMember(Name = "direction")]
            public DbVector2 Direction;

            public UpdateMovement(DbVector2 Direction)
            {
                this.Direction = Direction;
            }

            public UpdateMovement()
            {
                this.Direction = new();
            }

            string IReducerArgs.ReducerName => "update_movement";
        }
    }
}
