---
--- Generated by EmmyLua(https://github.com/EmmyLua)

--- DateTime: 2022/8/31 15:32
---

---@type UnityEngine.Object
Object = CS.UnityEngine.Object;
---@type UnityEngine.GameObject
GameObject = CS.UnityEngine.GameObject
---@type UnityEngine.Transform
Transform = CS.UnityEngine.Transform
---@type UnityEngine.Vector2
Vector2 = CS.UnityEngine.Vector2
---@type UnityEngine.Vector3
Vector3 = CS.UnityEngine.Vector3
---@type UnityEngine.Vector4
Vector4 = CS.UnityEngine.Vector4
---@type UnityEngine.Color
Color = CS.UnityEngine.Color
---@type UnityEngine.Rect
Rect = CS.UnityEngine.Rect
---@type UnityEngine.Quaternion
Quaternion = CS.UnityEngine.Quaternion
---@type XFramework.MonoLuaBehaviour
MonoLuaBehaviour = CS.MonoLuaBehaviour;
---@type XFramework.UpdateLuaBehaviour
UpdateLuaBehaviour = CS.XFramework.UpdateLuaBehaviour;
---@type XFramework.AudioManager
AudioManager = CS.XFramework.AudioManager.Instance;
---@type UnityEngine.WaitForSeconds
WaitForSeconds = CS.UnityEngine.WaitForSeconds;
---@type UnityEngine.WaitForEndOfFrame
WaitForEndOfFrame = CS.UnityEngine.WaitForEndOfFrame;

---@type UnityEngine.WaitForFixedUpdate
WaitForFixedUpdate = CS.UnityEngine.WaitForFixedUpdate;

---@type XFramework.UISystem
CsharpUISystem = CS.XFramework.UISystem.Instance;

---@type XFramework.AssetsManager
AssetsManager = CS.XFramework.AssetsManager.Instance;
---@type XFramework.LuaCallCSharp
LuaCallCSharp = CS.XFramework.LuaCallCSharp.Instance;
---@type UnityEngine.UI.LayoutRebuilder
LayoutRebuilder = CS.UnityEngine.UI.LayoutRebuilder;

---@type XFramework.UIHelper
CSharpUIHelper = CS.XFramework.UIHelper
---@type XFramework.UISystem
CSharpUISystem = CS.XFramework.UISystem.Instance;

---@type DG.Tweening.DOTween
DoTween = CS.DG.Tweening.DOTween

Ease = CS.DG.Tweening.Ease

---@type UnityEngine.Mathf
Mathf = CS.UnityEngine.Mathf;

---@type XFramework.UGUIPointerDownLuaBehaviour
UGUIPointerDownLuaBehaviour = CS.XFramework.UGUIPointerDownLuaBehaviour

---@type XFramework.UGUIPointerUpLuaBehaviour
UGUIPointerUpLuaBehaviour = CS.XFramework.UGUIPointerUpLuaBehaviour

---@type XFramework.UGUIPointerEnterLuaBehaviour
UGUIPointerEnterLuaBehaviour = CS.XFramework.UGUIPointerEnterLuaBehaviour

---@type XFramework.UGUIPointerExitLuaBehaviour
UGUIPointerExitLuaBehaviour = CS.XFramework.UGUIPointerExitLuaBehaviour

---@type XFramework.UGUIEndDragLuaBehaviour
UGUIEndDragLuaBehaviour = CS.XFramework.UGUIEndDragLuaBehaviour;

---@type UnityEngine.Microphone
Microphone = CS.UnityEngine.Microphone;

---@type System.TimeSpan
TimeSpan = CS.System.TimeSpan;

---@type UnityEngine.Application
Application = CS.UnityEngine.Application;

---@type XFramework.GameManager
GameManager = CS.XFramework.GameManager.Instance;



