// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BulletHandle : RemoteTableHandle<EventContext, Bullet>
        {
            protected override string RemoteTableName => "bullet";

            public sealed class BulletIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Bullet row) => row.BulletId;

                public BulletIdUniqueIndex(BulletHandle table) : base(table) { }
            }

            public readonly BulletIdUniqueIndex BulletId;

            internal BulletHandle(DbConnection conn) : base(conn)
            {
                BulletId = new(this);
            }

            protected override object GetPrimaryKey(Bullet row) => row.BulletId;
        }

        public readonly BulletHandle Bullet;
    }

    public sealed class BulletCols
    {
        public global::SpacetimeDB.Col<Bullet, int> BulletId { get; }
        public global::SpacetimeDB.Col<Bullet, string> BulletName { get; }
        public global::SpacetimeDB.Col<Bullet, float> Distance { get; }
        public global::SpacetimeDB.Col<Bullet, float> Speed { get; }
        public global::SpacetimeDB.Col<Bullet, DbVector2> Position { get; }
        public global::SpacetimeDB.Col<Bullet, DbVector2> Direction { get; }

        public BulletCols(string tableName)
        {
            BulletId = new global::SpacetimeDB.Col<Bullet, int>(tableName, "bullet_id");
            BulletName = new global::SpacetimeDB.Col<Bullet, string>(tableName, "bullet_name");
            Distance = new global::SpacetimeDB.Col<Bullet, float>(tableName, "distance");
            Speed = new global::SpacetimeDB.Col<Bullet, float>(tableName, "speed");
            Position = new global::SpacetimeDB.Col<Bullet, DbVector2>(tableName, "position");
            Direction = new global::SpacetimeDB.Col<Bullet, DbVector2>(tableName, "direction");
        }
    }

    public sealed class BulletIxCols
    {
        public global::SpacetimeDB.IxCol<Bullet, int> BulletId { get; }

        public BulletIxCols(string tableName)
        {
            BulletId = new global::SpacetimeDB.IxCol<Bullet, int>(tableName, "bullet_id");
        }
    }
}
