// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CharacterLevelDataHandle : RemoteTableHandle<EventContext, CharacterLevelDataConfig>
        {
            protected override string RemoteTableName => "character_level_data";

            public sealed class LevelUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CharacterLevelDataConfig row) => row.Level;

                public LevelUniqueIndex(CharacterLevelDataHandle table) : base(table) { }
            }

            public readonly LevelUniqueIndex Level;

            internal CharacterLevelDataHandle(DbConnection conn) : base(conn)
            {
                Level = new(this);
            }

            protected override object GetPrimaryKey(CharacterLevelDataConfig row) => row.Level;
        }

        public readonly CharacterLevelDataHandle CharacterLevelData;
    }

    public sealed class CharacterLevelDataCols
    {
        public global::SpacetimeDB.Col<CharacterLevelDataConfig, int> Level { get; }
        public global::SpacetimeDB.Col<CharacterLevelDataConfig, int> Exp { get; }

        public CharacterLevelDataCols(string tableName)
        {
            Level = new global::SpacetimeDB.Col<CharacterLevelDataConfig, int>(tableName, "level");
            Exp = new global::SpacetimeDB.Col<CharacterLevelDataConfig, int>(tableName, "exp");
        }
    }

    public sealed class CharacterLevelDataIxCols
    {
        public global::SpacetimeDB.IxCol<CharacterLevelDataConfig, int> Level { get; }

        public CharacterLevelDataIxCols(string tableName)
        {
            Level = new global::SpacetimeDB.IxCol<CharacterLevelDataConfig, int>(tableName, "level");
        }
    }
}
