// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DbChestHandle : RemoteTableHandle<EventContext, DbChest>
        {
            protected override string RemoteTableName => "db_chest";

            public sealed class ChestIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(DbChest row) => row.ChestId;

                public ChestIdUniqueIndex(DbChestHandle table) : base(table) { }
            }

            public readonly ChestIdUniqueIndex ChestId;

            internal DbChestHandle(DbConnection conn) : base(conn)
            {
                ChestId = new(this);
            }

            protected override object GetPrimaryKey(DbChest row) => row.ChestId;
        }

        public readonly DbChestHandle DbChest;
    }

    public sealed class DbChestCols
    {
        public global::SpacetimeDB.Col<DbChest, int> ChestId { get; }
        public global::SpacetimeDB.Col<DbChest, int> ItemId { get; }
        public global::SpacetimeDB.Col<DbChest, DbVector2> Position { get; }

        public DbChestCols(string tableName)
        {
            ChestId = new global::SpacetimeDB.Col<DbChest, int>(tableName, "chest_id");
            ItemId = new global::SpacetimeDB.Col<DbChest, int>(tableName, "item_id");
            Position = new global::SpacetimeDB.Col<DbChest, DbVector2>(tableName, "position");
        }
    }

    public sealed class DbChestIxCols
    {
        public global::SpacetimeDB.IxCol<DbChest, int> ChestId { get; }

        public DbChestIxCols(string tableName)
        {
            ChestId = new global::SpacetimeDB.IxCol<DbChest, int>(tableName, "chest_id");
        }
    }
}
