// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DiamondHandle : RemoteTableHandle<EventContext, Diamond>
        {
            protected override string RemoteTableName => "diamond";

            public sealed class DiamondIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Diamond row) => row.DiamondId;

                public DiamondIdUniqueIndex(DiamondHandle table) : base(table) { }
            }

            public readonly DiamondIdUniqueIndex DiamondId;

            internal DiamondHandle(DbConnection conn) : base(conn)
            {
                DiamondId = new(this);
            }

            protected override object GetPrimaryKey(Diamond row) => row.DiamondId;
        }

        public readonly DiamondHandle Diamond;
    }

    public sealed class DiamondCols
    {
        public global::SpacetimeDB.Col<Diamond, int> DiamondId { get; }
        public global::SpacetimeDB.Col<Diamond, DbVector2> Position { get; }
        public global::SpacetimeDB.Col<Diamond, int> Exp { get; }

        public DiamondCols(string tableName)
        {
            DiamondId = new global::SpacetimeDB.Col<Diamond, int>(tableName, "diamond_id");
            Position = new global::SpacetimeDB.Col<Diamond, DbVector2>(tableName, "position");
            Exp = new global::SpacetimeDB.Col<Diamond, int>(tableName, "exp");
        }
    }

    public sealed class DiamondIxCols
    {
        public global::SpacetimeDB.IxCol<Diamond, int> DiamondId { get; }

        public DiamondIxCols(string tableName)
        {
            DiamondId = new global::SpacetimeDB.IxCol<Diamond, int>(tableName, "diamond_id");
        }
    }
}
