// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GameConfigsHandle : RemoteTableHandle<EventContext, GameConfigs>
        {
            protected override string RemoteTableName => "game_configs";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(GameConfigs row) => row.Id;

                public IdUniqueIndex(GameConfigsHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GameConfigsHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(GameConfigs row) => row.Id;
        }

        public readonly GameConfigsHandle GameConfigs;
    }

    public sealed class GameConfigsCols
    {
        public global::SpacetimeDB.Col<GameConfigs, int> Id { get; }
        public global::SpacetimeDB.Col<GameConfigs, DbVector2> WordSize { get; }

        public GameConfigsCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<GameConfigs, int>(tableName, "id");
            WordSize = new global::SpacetimeDB.Col<GameConfigs, DbVector2>(tableName, "word_size");
        }
    }

    public sealed class GameConfigsIxCols
    {
        public global::SpacetimeDB.IxCol<GameConfigs, int> Id { get; }

        public GameConfigsIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<GameConfigs, int>(tableName, "id");
        }
    }
}
