// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GunmanUserHandle : RemoteTableHandle<EventContext, GunmanUser>
        {
            protected override string RemoteTableName => "GunmanUser";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(GunmanUser row) => row.Identity;

                public IdentityUniqueIndex(GunmanUserHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class UserIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(GunmanUser row) => row.UserId;

                public UserIdUniqueIndex(GunmanUserHandle table) : base(table) { }
            }

            public readonly UserIdUniqueIndex UserId;

            internal GunmanUserHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                UserId = new(this);
            }

            protected override object GetPrimaryKey(GunmanUser row) => row.Identity;
        }

        public readonly GunmanUserHandle GunmanUser;
    }

    public sealed class GunmanUserCols
    {
        public global::SpacetimeDB.Col<GunmanUser, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<GunmanUser, int> UserId { get; }
        public global::SpacetimeDB.Col<GunmanUser, int> Gold { get; }
        public global::SpacetimeDB.Col<GunmanUser, int> Diamond { get; }

        public GunmanUserCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<GunmanUser, SpacetimeDB.Identity>(tableName, "identity");
            UserId = new global::SpacetimeDB.Col<GunmanUser, int>(tableName, "user_id");
            Gold = new global::SpacetimeDB.Col<GunmanUser, int>(tableName, "gold");
            Diamond = new global::SpacetimeDB.Col<GunmanUser, int>(tableName, "diamond");
        }
    }

    public sealed class GunmanUserIxCols
    {
        public global::SpacetimeDB.IxCol<GunmanUser, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<GunmanUser, int> UserId { get; }

        public GunmanUserIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<GunmanUser, SpacetimeDB.Identity>(tableName, "identity");
            UserId = new global::SpacetimeDB.IxCol<GunmanUser, int>(tableName, "user_id");
        }
    }
}
