// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OnlinePlayerOutUserHandle : RemoteTableHandle<EventContext, Player>
        {
            protected override string RemoteTableName => "online_player_out_user";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Player row) => row.Identity;

                public IdentityUniqueIndex(OnlinePlayerOutUserHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            public sealed class PlayerIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(Player row) => row.PlayerId;

                public PlayerIdUniqueIndex(OnlinePlayerOutUserHandle table) : base(table) { }
            }

            public readonly PlayerIdUniqueIndex PlayerId;

            public sealed class UserIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(Player row) => row.UserId;

                public UserIdIndex(OnlinePlayerOutUserHandle table) : base(table) { }
            }

            public readonly UserIdIndex UserId;

            internal OnlinePlayerOutUserHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                PlayerId = new(this);
                UserId = new(this);
            }

            protected override object GetPrimaryKey(Player row) => row.Identity;
        }

        public readonly OnlinePlayerOutUserHandle OnlinePlayerOutUser;
    }

    public sealed class OnlinePlayerOutUserCols
    {
        public global::SpacetimeDB.Col<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<Player, int> PlayerId { get; }
        public global::SpacetimeDB.Col<Player, DbVector2> Position { get; }
        public global::SpacetimeDB.Col<Player, DbVector2> AttackDirection { get; }
        public global::SpacetimeDB.Col<Player, DbVector2> MovementDirection { get; }
        public global::SpacetimeDB.Col<Player, int> Level { get; }
        public global::SpacetimeDB.Col<Player, int> UserId { get; }
        public global::SpacetimeDB.Col<Player, int> Exp { get; }
        public global::SpacetimeDB.Col<Player, float> Speed { get; }
        public global::SpacetimeDB.Col<Player, bool> IsMovement { get; }
        public global::SpacetimeDB.Col<Player, string> WeaponId { get; }

        public OnlinePlayerOutUserCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<Player, SpacetimeDB.Identity>(tableName, "identity");
            PlayerId = new global::SpacetimeDB.Col<Player, int>(tableName, "player_id");
            Position = new global::SpacetimeDB.Col<Player, DbVector2>(tableName, "position");
            AttackDirection = new global::SpacetimeDB.Col<Player, DbVector2>(tableName, "attack_direction");
            MovementDirection = new global::SpacetimeDB.Col<Player, DbVector2>(tableName, "movement_direction");
            Level = new global::SpacetimeDB.Col<Player, int>(tableName, "level");
            UserId = new global::SpacetimeDB.Col<Player, int>(tableName, "user_id");
            Exp = new global::SpacetimeDB.Col<Player, int>(tableName, "exp");
            Speed = new global::SpacetimeDB.Col<Player, float>(tableName, "speed");
            IsMovement = new global::SpacetimeDB.Col<Player, bool>(tableName, "is_movement");
            WeaponId = new global::SpacetimeDB.Col<Player, string>(tableName, "weapon_id");
        }
    }

    public sealed class OnlinePlayerOutUserIxCols
    {
        public global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.IxCol<Player, int> PlayerId { get; }
        public global::SpacetimeDB.IxCol<Player, int> UserId { get; }

        public OnlinePlayerOutUserIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<Player, SpacetimeDB.Identity>(tableName, "identity");
            PlayerId = new global::SpacetimeDB.IxCol<Player, int>(tableName, "player_id");
            UserId = new global::SpacetimeDB.IxCol<Player, int>(tableName, "user_id");
        }
    }
}
