---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 31032.
--- DateTime: 2023/12/21 14:37
---
CSharpCallLua ={}
---@type XFramework.LuaUISystem
local LuaUISystem = CS.XFramework.LuaUISystem.Instance;


function CSharpCallLua.Init()
    print('CSharpCallLua.Init')
    LuaUISystem.openUI = CSharpCallLua.OpenUI;
    LuaUISystem.closeUI = UISystem.CloseUI;
    LuaUISystem.openUIAsync = CSharpCallLua.OpenUIAsync;
end

function CSharpCallLua.OpenUI(uiName)
    print('OpenUI ..........')
    UISystem.OpenUI(uiName)
end


function CSharpCallLua.OpenUIAsync(uiName,callback)
    UISystem.OpenUIAsync(uiName,function(ui) 
        callback(ui)
    end)
end